<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
Layout::includeLayout('indexheader'); ?>

    <head>
        <style>
            table, th, td {
                border: 1px solid black;
                border-collapse: collapse;
            }
        </style>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    </head>


    <body>
        <div class="container" style="margin-top: 150px;">
            <h1>Aviões:</h1>
            <br>
            <a href="<?= Url::toRoute('gestor/gestorAvioesInserir')?>">Inserir novo avião</a>
            <br>
            <?php $avioes=\ArmoredCore\WebObjects\Data::get('avioes'); ?>
            <table style="width:100%">
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>Lotação</th>
                    <th>Tipo</th>
                    <th colspan="2">Gestão</th>
                </tr>
                <?php foreach($avioes as $aviao){?>
                    <tr>
                        <td><?= $aviao->plane_id ?></td>
                        <td><?= $aviao->name ?></td>
                        <td><?= $aviao->capacity ?></td>
                        <td><?= $aviao->type ?></td>
                        <td><a href="<?= Url::toRoute('gestor/removerAviao', $aviao->plane_id) ?>" class="btn btn-warning" role="button">Eliminar</a></td>
                        <td><a href="<?= Url::toRoute('gestor/gestorAvioesAlterar', $aviao->plane_id) ?>" class="btn btn-info" role="button">Alterar</a></td>
                    </tr>
                <?php } ?>
            </table>
            <br>
            <a href="<?= Url::toRoute('gestor/gestor')?>">Voltar a página inicial</a>
        </div>
    </body>


    

<?php Layout::includeLayout('footer')?> 