<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
Layout::includeLayout('headerback'); ?>

    <head>
        <style>
            table, th, td {
                border: 1px solid black;
                border-collapse: collapse;
            }
        </style>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    </head>


    <body>
        <div class="container" style="margin-top: 150px;">
            <h1>Voos:</h1>
            <br>
            <a href="<?= Url::toRoute('gestor/gestorVoosInserir')?>">Inserir novo voo</a>
            <br>
            <?php $voos=\ArmoredCore\WebObjects\Data::get('voos'); ?>
            <table style="width:100%">
                <tr>
                    <th>Id</th>
                    <th>Origem</th>
                    <th>Destino</th>
                    <th>Preço</th>
                    <th>Data/Hora Partida</th>
                    <th>Data/Hora Chegada</th>
                    <th colspan="3">Gestão</th>
                </tr>
                <?php foreach($voos as $voo){?>
                    <tr>
                        <td><?= $voo->flight_id ?></td>
                        <td><?= $voo->origin_id ?></td>
                        <td><?= $voo->destiny_id ?></td>
                        <td><?= $voo->price ?></td>
                        <td><?= $voo->departure ?></td>
                        <td><?= $voo->arrival ?></td>
                        <td><a href="<?= Url::toRoute('gestor/removerVoo', $voo->flight_id) ?>" class="btn btn-warning" role="button">Eliminar</a></td>
                        <td><a href="<?= Url::toRoute('gestor/gestorVoosAlterar', $voo->flight_id) ?>" class="btn btn-info" role="button">Alterar</a></td>
                        <td><a href="<?= Url::toRoute('gestor/gestorGerirEscalas', $voo->flight_id) ?>" class="btn btn-info" role="button">Gerir Escalas</a></td>
                    </tr>
                <?php } ?>
            </table>
            <br>
            <a href="<?= Url::toRoute('gestor/gestor')?>">Voltar a página inicial</a>
        </div>
    </body>


    

<?php Layout::includeLayout('footer')?> 
