<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;

Layout::includeLayout('headerback'); ?>

<?php $aviao = Data::get('aviao')?>
<?php ErrMgr::attach($aviao) ?>

    <!-- Header -->
    <!--<header id="head">
        <div class="container">
            <div class="row">
                <h1 class="lead"><b>RAR Aeroportos</b><br><small><b>Desde</b> 2021</small><br>A voar consigo</h1>
                <p class="tagline">Desenvolvendo as melhores viagens. Sempre com os melhores profisionais.</p>
                <p><a class="btn btn-action btn-lg" role="button" href="<?= Url::toRoute('home/start')?>">Comece agora</a></p>
                <p class="small">Por<i> Ricardo, André, Rafael</i></p>
            </div>
        </div>
    </header>-->
    <!-- /Header -->
    <head>
        
    </head>


    <body>
        <div class="container" style="margin-top: 150px;">
            <h2>Dados do avião:</h2><br>

            <form method="POST" action="<?php Url::toRoute('gestor/AlterarAviao', $aviao->plane_id)?>">

                <div class="top-margin">
                    <label>Nome <span class="text-danger">*</span></label>
                    <input type="text" value="<?=$aviao->name?>" name="name" class="form-control" placeholder="Insira o nome">
                    <?= ErrMgr::bind('name') ?>
                </div>

                <div class="top-margin">
                    <label>Lotação <span class="text-danger">*</span></label>
                    <input type="text" value="<?=$aviao->capacity?>" name="capacity" class="form-control" placeholder="Insira a lotação">
                    <?= ErrMgr::bind('capacity') ?>
                </div>

                <div class="top-margin">
                    <label>Tipo <span class="text-danger">*</span></label>
                    <input type="text" value="<?=$aviao->type?>" name="type" class="form-control" placeholder="Insira o tipo">
                    <?= ErrMgr::bind('type') ?>
                </div>

                <div class="top-margin">
					<button class="btn btn-action" type="submit">Alterar</button>
				</div>
            </form> 

        </div>
    </body>

<?php Layout::includeLayout('footer')?> 
