<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
Layout::includeLayout('headerback'); ?>

    <head>
        <style>
            table, th, td {
                border: 1px solid black;
                border-collapse: collapse;
            }
        </style>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    </head>


    <body>
        <div class="container" style="margin-top: 150px;">
            <h1>Escalas do Voo:</h1>
            <?php $idvoo=\ArmoredCore\WebObjects\Data::get('idvoo'); ?>
            <br>
            <a href="<?= Url::toRoute('gestor/gestorGerirEscalasInserir', $idvoo)?>">Inserir nova escala</a>
            <br>
            <?php $escalas=\ArmoredCore\WebObjects\Data::get('escalas'); ?>
            <table style="width:100%">
                <tr>
                    <th>Id da escala</th>
                    <th>Ordem</th>
                    <th>Gestão</th>
                </tr>
                <?php foreach($escalas as $escala){?>
                    <tr>
                        <td><?= $escala->scale_id ?></td>
                        <td><?= $escala->ordering ?></td>
                        <td><a href="<?= Url::toRoute('gestor/removerEscalaVoo', $escala->id) ?>" class="btn btn-warning" role="button">Eliminar</a></td>
                    </tr>
                <?php } ?>
            </table>
            <br>
            <a href="<?= Url::toRoute('gestor/gestorVoos')?>">Voltar a página dos voos</a>
        </div>
    </body>


    

<?php Layout::includeLayout('footer')?> 
