<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;

Layout::includeLayout('headerback'); ?>

<?php $escala = Data::get('escala')?>
<?php ErrMgr::attach($escala) ?>

    <!-- Header -->
    <!--<header id="head">
        <div class="container">
            <div class="row">
                <h1 class="lead"><b>RAR Aeroportos</b><br><small><b>Desde</b> 2021</small><br>A voar consigo</h1>
                <p class="tagline">Desenvolvendo as melhores viagens. Sempre com os melhores profisionais.</p>
                <p><a class="btn btn-action btn-lg" role="button" href="<?= Url::toRoute('home/start')?>">Comece agora</a></p>
                <p class="small">Por<i> Ricardo, André, Rafael</i></p>
            </div>
        </div>
    </header>-->
    <!-- /Header -->
    <head>
        
    </head>


    <body>
        <div class="container" style="margin-top: 150px;">
            <h2>Dados da escala do voo:</h2><br>

            <?php $escalas=\ArmoredCore\WebObjects\Data::get('escalasList'); ?>
            <?php $idvoo=\ArmoredCore\WebObjects\Data::get('idvoo'); ?>

            <form method="POST" action="<?php Url::toRoute('gestor/InserirEscalaVoo')?>">

                <div class="top-margin">
                    <label>Escala <span class="text-danger">*</span></label>

                    <select name="scale_id" class="form-control">
                    <?php foreach($escalas as $esc){?>

                        <option value="<?=$esc->scale_id?>"><?=$esc->description?></option>

                <?php } ?>
                    </select>

                    <?= ErrMgr::bind('scale_id') ?>
                </div>

                <div class="top-margin">
                    <label>Ordem <span class="text-danger">*</span></label>
                    <input type="text" value="<?=$escala->ordering?>" name="ordering" class="form-control" placeholder="Insira a ordem">
                    <?= ErrMgr::bind('ordering') ?>
                </div>

                <input type="hidden" name="flight_id" value="<?=$idvoo?>"></input>

                <div class="top-margin">
					<button class="btn btn-action" type="submit">Inserir</button>
				</div>
            </form> 

        </div>
    </body>

<?php Layout::includeLayout('footer')?> 
