<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
Layout::includeLayout('headerback'); ?>

    <head>
        <style>
            table, th, td {
                border: 1px solid black;
                border-collapse: collapse;
            }
        </style>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    </head>


    <body>
        <div class="container" style="margin-top: 150px;">
            <h1>Escalas:</h1>
            <br>
            <a href="<?= Url::toRoute('gestor/gestorEscalasInserir')?>">Inserir nova escala</a>
            <br>
            <?php $escalas=\ArmoredCore\WebObjects\Data::get('escalas'); ?>
            <table style="width:100%">
                <tr>
                    <th>Id</th>
                    <th>Origem</th>
                    <th>Destino</th>
                    <th>Descrição</th>
                    <th>Distancia</th>
                    <th>Data/Hora Partida</th>
                    <th>Data/Hora Chegada</th>
                    <th>Nº de passagens</th>
                    <th>Avião</th>
                    <th colspan="2">Gestão</th>
                </tr>
                <?php foreach($escalas as $escala){?>
                    <tr>
                        <td><?= $escala->scale_id ?></td>
                        <td><?= $escala->origin_id ?></td>
                        <td><?= $escala->destiny_id ?></td>
                        <td><?= $escala->description ?></td>
                        <td><?= $escala->distance ?></td>
                        <td><?= $escala->departure ?></td>
                        <td><?= $escala->arrival ?></td>
                        <td><?= $escala->numbertickets ?></td>
                        <td><?= $escala->plane_id ?></td>
                        <td><a href="<?= Url::toRoute('gestor/removerEscala', $escala->scale_id) ?>" class="btn btn-warning" role="button">Eliminar</a></td>
                        <td><a href="<?= Url::toRoute('gestor/gestorEscalasAlterar', $escala->scale_id) ?>" class="btn btn-info" role="button">Alterar</a></td>
                    </tr>
                <?php } ?>
            </table>
            <br>
            <a href="<?= Url::toRoute('gestor/gestor')?>">Voltar a página inicial</a>
        </div>
    </body>


    

<?php Layout::includeLayout('footer')?> 
