<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;

Layout::includeLayout('indexheader'); ?>

<?php $utilizador = Data::get('utilizador')?>
<?php ErrMgr::attach($utilizador) ?>

    <!-- Header -->
    <!--<header id="head">
        <div class="container">
            <div class="row">
                <h1 class="lead"><b>RAR Aeroportos</b><br><small><b>Desde</b> 2021</small><br>A voar consigo</h1>
                <p class="tagline">Desenvolvendo as melhores viagens. Sempre com os melhores profisionais.</p>
                <p><a class="btn btn-action btn-lg" role="button" href="<?= Url::toRoute('home/start')?>">Comece agora</a></p>
                <p class="small">Por<i> Ricardo, André, Rafael</i></p>
            </div>
        </div>
    </header>-->
    <!-- /Header -->
    <head>
        
    </head>


    <body>
        <div class="container" style="margin-top: 150px;">
            <h2>Dados do gestor de voo:</h2><br>

            <form method="POST" action="<?php Url::toRoute('admistrador/InserirGestor')?>">

                <div class="top-margin">
                    <label>Nome <span class="text-danger">*</span></label>
                    <input type="text" value="<?=$utilizador->name?>" name="name" class="form-control" placeholder="Insira um nome">
                    <?= ErrMgr::bind('name') ?>
                </div>

                <div class="top-margin">
                    <label>Rua <span class="text-danger">*</span></label>
                    <input type="text" value="<?=$utilizador->road?>" name="road" class="form-control" placeholder="Insira a rua">
                    <?= ErrMgr::bind('road') ?>
                </div>

                <div class="top-margin">
                    <label>Localidade <span class="text-danger">*</span></label>
                    <input type="text" value="<?=$utilizador->location?>" name="location" class="form-control" placeholder="Insira a localidade">
                    <?= ErrMgr::bind('location') ?>
                </div>

                <div class="top-margin">
                    <label>Código postal <span class="text-danger">*</span></label>
                    <input type="text" value="<?=$utilizador->postalcode?>" name="postalcode" class="form-control" placeholder="Insira o codigo postal">
                    <?= ErrMgr::bind('postalcode') ?>
                </div>

                <div class="top-margin">
                    <label>Data de nascimento <span class="text-danger">*</span></label>
                    <input type="datetime-local" value="<?=$utilizador->birthdate?>" name="birthdate" class="form-control" placeholder="Insira a data de nascimento">
                    <?= ErrMgr::bind('birthdate') ?>
                </div>

                <div class="top-margin">
                    <label>Email <span class="text-danger">*</span></label>
                    <input type="text" value="<?=$utilizador->email?>" name="email" class="form-control" placeholder="Insira o email">
                    <?= ErrMgr::bind('email') ?>
                </div>

                <div class="top-margin">
                    <label>NIF <span class="text-danger">*</span></label>
                    <input type="text" value="<?=$utilizador->NIF?>" name="NIF" class="form-control" placeholder="Insira o NIF">
                    <?= ErrMgr::bind('NIF') ?>
                </div>

                <div class="top-margin">
                    <label>Telefone <span class="text-danger">*</span></label>
                    <input type="text" value="<?=$utilizador->phone?>" name="phone" class="form-control" placeholder="Insira o telefone">
                    <?= ErrMgr::bind('phone') ?>
                </div>

                <div class="top-margin">
                    <label>Username <span class="text-danger">*</span></label>
                    <input type="text" value="<?=$utilizador->username?>" name="username" class="form-control" placeholder="Insira o username">
                    <?= ErrMgr::bind('username') ?>
                </div>

                <div class="top-margin">
                    <label>Password <span class="text-danger">*</span></label>
                    <input type="text" value="<?=$utilizador->pass?>" name="pass" class="form-control" placeholder="Insira a password">
                    <?= ErrMgr::bind('pass') ?>
                </div>

                <input type="hidden" name="profiletype" value="gestor"></input>

                <div class="top-margin">
					<button class="btn btn-action" type="submit">Inserir</button>
				</div>
            </form> 

        </div>
    </body>


<?php Layout::includeLayout('footer')?> 